name = "KiteUtils"
uuid = "90980105-b163-44e5-ba9f-8b1c83bb0533"
authors = ["Uwe Fechner <uwe.fechner.msc@gmail.com> and contributors"]
version = "0.6.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Arrow = "2.7.1"
CSV = "0.10.13"
DocStringExtensions = "0.9.3"
Parameters = "0.12.3"
PrecompileTools = "1.2.1"
RecursiveArrayTools = "3.3.3"
Rotations = "1.7.0"
StaticArrays = "1.9.3"
StructArrays = "0.6.18"
StructTypes = "1.10.0"
YAML = "0.4.9"
julia = "1.9, 1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "KiteUtils", "BenchmarkTools"]
