name = "KiteUtils"
uuid = "90980105-b163-44e5-ba9f-8b1c83bb0533"
authors = ["Uwe Fechner <uwe.fechner.msc@gmail.com> and contributors"]
version = "0.4.2"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Arrow = "2"
CSV = "0.10"
DocStringExtensions = "0.8, 0.9"
Parameters = "0.12"
RecursiveArrayTools = "2"
Rotations = "1.1, 1.2, 1.3"
StaticArrays = "=1.2.5, 1.3, 1.4"
StructArrays = "0.6"
TestEnv = "1"
YAML = "0.4"
julia = "1.6, 1.7, 1.8"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "KiteUtils", "BenchmarkTools"]
